# =====================================
# GitHub Actions Workflow: compile.yml
# Purpose: Build & export BitChat as .ipa (no tests)
# =====================================

name: Compile Only

on:
  # Trigger on push or PR to main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    # macOS runner required for Xcode and iOS SDK
    runs-on: macos-15  # Change this if GitHub updates macOS versions

    steps:
    # Checkout source code
    - name: Checkout
      uses: actions/checkout@v4

    # Set up Xcode version
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "16.4"
        # Update this if BitChat requires newer Xcode/iOS SDK

    # Generate Xcode project from project.yml using XcodeGen
    - name: XcodeGen
      uses: xavierLowmiller/xcodegen-action@1.2.4
      with:
        spec: project.yml
        version: 2.43.0
        # If project.yml or XcodeGen version changes, update here

    # Archive app for real device
- name: Archive app
  run: |
    set -o pipefail && xcodebuild archive \
      -scheme "bitchat (iOS)" \
      -sdk iphoneos \
      -configuration Release \
      -archivePath $GITHUB_WORKSPACE/build/BitChat.xcarchive

    # Export unsigned IPA for sideloading/signing later
    - name: Export IPA
      run: |
        cat > ExportOptions.plist <<EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>method</key>
          <string>development</string>
          <key>signingStyle</key>
          <string>automatic</string>
          <key>compileBitcode</key>
          <false/>
          <key>stripSwiftSymbols</key>
          <true/>
          <key>destination</key>
          <string>export</string>
          <key>thinning</key>
          <string>&lt;none&gt;</string>
        </dict>
        </plist>
        EOF

        xcodebuild -exportArchive \
          -archivePath $GITHUB_WORKSPACE/build/BitChat.xcarchive \
          -exportPath $GITHUB_WORKSPACE/build/ipa \
          -exportOptionsPlist ExportOptions.plist

    # Upload .ipa as downloadable artifact
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: BitChat-ipa
        path: build/ipa

# ===
# NOTES:
# - Your device: iPhone 16 (base)
# - iOS version: 18.5 (upgrading to 26 public beta soon)
# - Simulator target and OS are not used here since no tests run.
# - If you add tests later, remember to update simulator device and OS in the workflow.
# - Keep Xcode version updated to match iOS SDK compatibility.
# ===
